import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MusicProvider } from "./context/MusicContext";
import { WalletProvider } from "./context/WalletContext";
import { ThemeProvider } from "./components/ThemeProvider";
import { StarknetProvider } from "./components/StarknetProvider";
import Header from "./components/Header";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Suspense fallback={<div>Loading...</div>}>
        <ThemeProvider>
          <StarknetProvider>
            <WalletProvider>
              <MusicProvider>
                <Header />
                {children}
              </MusicProvider>
            </WalletProvider>
          </StarknetProvider>
        </ThemeProvider>
      </Suspense>
      </body>
    </html>
  );
}
