name: Contracts CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
    
      - name: Install Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.10.1"

      - name: Install asdf
        uses: asdf-vm/actions/setup@v3

      - name: Install Starknet Foundry
        run: |
          asdf plugin add starknet-foundry || true
          asdf install starknet-foundry latest
          asdf global starknet-foundry latest
      - name: Build and Test ERC20 Contract
        run: |
          cd erc/erc20
          scarb build
          scarb test
          scarb fmt --check
      - name: Build and Test ERC721 Contract
        run: |
          cd erc/erc721
          scarb build
          scarb test
          scarb fmt --check